apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels: 
    group: myapp

spec:
  selector:
    matchLabels:
      env: test
  replicas: 3

  template:
    metadata:
      name: nginx
      labels:
        env: test

    spec:
      containers:
        - name: nginx-containter
          image: nginx
