apiVersion: v1
kind: Service
metadata:
  name: k8s-course-service-ci
  labels: 
    group: k8s-course

spec:
  type: ClusterIP
  ports:
    - port: 30002
      targetPort: 80
  selector:
    env: test