apiVersion: v1
kind: Service
metadata:
  name: k8s-course-service
  labels: 
    group: k8s-course

spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80 optional if the same
      nodePort: 30001
  selector:
    env: test